CREATE SCHEMA IF NOT EXISTS TEST;
SET SCHEMA TEST;

CREATE TABLE ITEM
(
  ID BIGINT auto_increment PRIMARY KEY,
  COMPOSITION VARCHAR2(100),
  DESCRIPTION VARCHAR2(100),
  PRICE DECIMAL(20, 2),
  REFERENCE INT
);

CREATE TABLE CATEGORY
(
  ID BIGINT PRIMARY KEY,
  NAME VARCHAR2(100)
);

