CREATE SCHEMA IF NOT EXISTS TEST;
SET SCHEMA TEST;

CREATE TABLE TEAM
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  NAME VARCHAR(255) NOT NULL
);

CREATE TABLE ITEM
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  COMPOSITION VARCHAR(255),
  DESCRIPTION VARCHAR(255),
  PRICE DOUBLE NOT NULL,
  REFERENCE INT NOT NULL,
  TEAM_ID BIGINT,
  FOREIGN KEY (TEAM_ID) REFERENCES TEAM (ID)
);
CREATE INDEX FK_R9OYQ3MVM2MI8EJYU07B2EN3Q_INDEX_2 ON ITEM (TEAM_ID);

CREATE TABLE STOCK
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  SIZE VARCHAR2(2) NOT NULL,
  AVAILABLE INTEGER NOT NULL,
  ITEM_ID BIGINT NOT NULL,
  FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ID)
);
CREATE INDEX FK_QHSHSANO1H52WBS6GRBXBABWK_INDEX_4 ON STOCK (ITEM_ID);



