CREATE TABLE CLIENT(ID INT PRIMARY KEY,
   NAME VARCHAR(255), FIRSTNAME VARCHAR(255), EMAIL VARCHAR(255), PASSWORD  VARCHAR(255));
   
 CREATE TABLE ITEM(ID INT PRIMARY KEY,COMPOSITION VARCHAR(255), 
 	DESCRIPTION VARCHAR(255),  PRICE DOUBLE, REFERENCE INT);
 
 CREATE TABLE ORDER_ITEM(ID INT PRIMARY KEY,
 	REFERENCEID INT, QUANTITY INT);
 	
 CREATE TABLE STOCK(ID INT PRIMARY KEY, REFERENCE_ID INT, SIZE VARCHAR(5), STOCK INT);
 
 CREATE TABLE REFERENCE_SIZE(SIZE VARCHAR(5) PRIMARY KEY);